[tool.poetry]
name = "url-preview-api"
version = "0.1.0"
description = "The endpoint is designed to accept a URL from the user and performs the following functions in sequence: It retrieves the content of the specified webpage, including all textual and multimedia content. It then proceeds to extract relevant metadata from the content, focusing on elements like the page title, description, keywords, and any available meta tags that can enrich the extracted data set. Following the extraction, the system generates a comprehensive preview snippet. This snippet includes the page title, a concise description derived from either the meta description tag or a summary of the page content, and a thumbnail image, which is selected based on relevance and representation of the webpage content. The produced structured preview data encompasses all the aforementioned elements and is formatted for optimal use in link sharing across social media platforms, embedding in webpages, or any other scenario where a concise, informative preview of the webpage content is required. This process relies on a tech stack consisting of Python as the programming language, utilizing FastAPI for creating the efficient and scalable API endpoint. PostgreSQL serves as the database to manage and store extracted content and metadata, while Prisma is employed as the ORM for facilitating interaction between the application and the database. The system is designed with best practices for content extraction and metadata retrieval, ensuring respect for robots.txt, managing request rates to prevent server overload, and using legal and responsible data handling methods. The approach enhances user engagement by providing clear, accessible, and informative webpage previews."
authors = ["AutoGPT <info@agpt.co>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"
fastapi = "^0.75.1"
httpx = "^0.23.0"
prisma = "*"
pydantic = "*"
uvicorn = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
